# -*- coding: utf-8 -*-
"""Stommel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fg_Baguo5FxrjD0Ke8cSQe59fEfehwRk
"""

#@title Modelo corrida
import numpy as np

Lx, Ly = 4000000, 2000000 # m
Dx, Dy = 10000, 10000 # m
tau0 = 0.25 # N/m2
rho0 = 1025 # Kg / m3
D0 = 2500 # m
K1, K2, K3 = 100000*2e-11, 250000*2e-11, 500000*2e-11
B = 2e-11
K = K1

xpoints, ypoints = np.arange(0, Lx + Dx, Dx), np.arange(0, Ly + Dy, Dy)
X,Y = np.meshgrid(xpoints, ypoints)
Nx, Ny = len(xpoints), len(ypoints)

# Estado inicial
psi = np.zeros((Nx, Ny))

# Parámetros
ax = K/(Dx**2) + B/(2*Dx) # psi[i+1, j]
bx = K/(Dx**2) - B/(2*Dx) # psi[i-1, j]
cy = K/(Dy**2) # psi[i, j+1]
dy = K/(Dy**2) # psi[i, j-1]
exy = -2*K*(1/(Dx**2)+1/(Dy**2)) #psi[i,j]

# Coeficientes SOR
omega = 1.7
tolerancia = 1e-6
iteraciones = 20000

# Forzante por viento
fv = - ((tau0*np.pi)/(rho0*D0*Ly))*np.sin((np.pi*ypoints)/Ly)

Punto_b_oeste = []
Punto_centro = []
Punto_b_este = []

for it in range(iteraciones):

    resto_0 = 0.0

    for i in range(1, Nx-1):
        for j in range(1, Ny-1):

            resto = (
                ax*psi[i+1, j] +
                bx*psi[i-1, j] +
                cy*psi[i, j+1] +
                dy*psi[i, j-1] +
                exy*psi[i, j] -
                fv[j]
            )

            psi[i, j] -= omega * resto/ exy
            resto_0 = max(resto_0, abs(resto/exy))

    if it == 250:
      psi_250it = psi.copy()
    if it == 750:
      psi_750it = psi.copy()

    Punto_b_oeste.append(psi[50, 100])
    Punto_centro.append(psi[200, 100])
    Punto_b_este.append(psi[250,100])

    psi[0, :]  = 0
    psi[-1, :] = 0
    psi[:, 0]  = 0
    psi[:, -1] = 0

    # Criterio de convergencia
    if resto_0 < tolerancia:
        print(f"Convergió en {it} iteraciones")
        break
else:
    print("No convergió")

if K == K1:
  np.save(f'psi1_Dx{Dx}.npy', psi)
  np.save('psi1_borde.npy', Punto_b_oeste)
  np.save('psi1_centro.npy', Punto_centro)
  np.save('psi1_b_este.npy', Punto_b_este)
elif K == K2:
  np.save(f'psi2_Dx{Dx}.npy', psi)
  np.save('psi2_borde.npy', Punto_b_oeste)
  np.save('psi2_centro.npy', Punto_centro)
  np.save('psi2_b_este.npy', Punto_b_este)
else:
  np.save(f'psi3_Dx{Dx}.npy', psi)
  np.save('psi3_borde.npy', Punto_b_oeste)
  np.save('psi3_centro.npy', Punto_centro)
  np.save('psi3_b_este.npy', Punto_b_este)